# This step clones the demo-env repository
- name: 'gcr.io/cloud-builders/gcloud'
  id: Clone env repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud source repos clone demo-env && \
    cd demo-env && \
    git checkout candidate && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes.yml.tpl | \
     sed "s/COMMIT_SHA/${SHORT_SHA}/g" > demo-env/kubernetes.yml

# This step pushes the manifest back to demo-env
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    cd demo-env && \
    git add kubernetes.yml && \
    git commit -m "Deploying image gcr.io/${PROJECT_ID}/demo-cicd:${SHORT_SHA}
    Built from commit ${COMMIT_SHA} of repository demo-app
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    git push origin candidate